- id: transcrypt
  name: transcrypt
  description: transparently encrypt files within a git repository
  entry: ./scripts/transcrypt.sh
  language: script
  stages:
    - commit
  pass_filenames: false

- id: pip-compile-requirements
  name: pip-compile requirements.txt
  description: pip-compile requirements.txt
  entry: bash -c "python3.9 -m venv ./venv && source ./venv/bin/activate && pip-compile -q --no-annotate --allow-unsafe --rebuild --output-file ./requirements/requirements.txt ./setup.cfg && git add ./requirements/requirements.txt"
  language: system
  stages:
    - commit
  pass_filenames: false

- id: pip-compile-requirements-dev
  name: pip-compile requirements_dev.txt
  description: pip-compile requirements.txt
  entry: bash -c "python3.9 -m venv ./venv && source ./venv/bin/activate && pip-compile -q --extra dev --no-annotate --allow-unsafe --rebuild --output-file ./requirements/requirements_dev.txt ./setup.cfg && git add ./requirements/requirements_dev.txt"
  language: system
  stages:
    - commit
  pass_filenames: false
