- id: transcrypt
  name: transcrypt
  description: transparently encrypt files within a git repository
  entry: ./scripts/transcrypt.sh
  language: script
  stages:
    - commit
  pass_filenames: false
