# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: make-requirements-dir
        name: make requirements directory
        language: system
        entry: mkdir -p ./requirements
        pass_filenames: false

  - repo: local
    hooks:
      - id: pip-compile
        name: pip-compile requirements
        language: system
        entry: pwd
        pass_filenames: false

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
      - id: pip-compile
        name: pip-compile setup.py
        files: ^(setup\.cfg)$
        pass_filenames: True

  - repo: https://github.com/j5pu/precommit
    rev: v0.0.7
    hooks:
      - id: pip-compile-requirements
      - id: pip-compile-requirements-dev
      - id: transcrypt
