- id: transcrypt
  name: transcrypt
  description: transparently encrypt files within a git repository
  entry: ./scripts/transcript.sh
  language: script
  stages:
    - commit
  pass_filenames: false
